# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
- env:
  - CGO_ENABLED=0
  targets:
  - linux_amd64_v1
  - windows_amd64_v1
  - darwin_arm64
  ldflags:
  - -s -w -X version.Version={{.Version}} -X version.Commit={{.Commit}} -X version.Date={{.Date}}

archives:
  - formats: [tar.gz]
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

